Add cobwebs, strings, and placeable tripwires (no function)
dragonfly-tech/dragonfly pull request #437
Opened 2022-03-03 02:17 UTC by Prim69

2022-03-07 15:41 UTC, Prim69 commented
Could I get a review on this please

2022-03-07 16:25 UTC, Prim69 commented on server/block/cobweb.go
> +// Cobweb is a block that can slow down entity movement and negate fall damage.
I tested it and didn't seem to take any fall damage

2022-03-07 23:58 UTC, Prim69 commented
Just tested fall damage negation, works perfectly

2022-03-11 01:20 UTC, Prim69 commented
Could someone review this please

2022-03-11 03:39 UTC, DaPigGuy requested changes
Cobwebs are missing physics for non player entities

2022-03-13 21:31 UTC, Prim69 commented
> Cobwebs are missing physics for non player entities

Any idea how I can do that?

2022-08-02 05:14 UTC, Prim69 commented
How would i do the physics here for non player entities?

2022-08-15 01:59 UTC, Prim69 commented
i say we merge this because water doesn't have physics for non player entities either

2026-05-07 08:36 UTC, closed without merging